# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170707_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='总流量',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField()),
                ('value', models.IntegerField()),
                ('times', models.CharField(max_length=100)),
                ('in_or_out', models.CharField(max_length=100)),
            ],
        ),
    ]
