# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_总流量'),
    ]

    operations = [
        migrations.CreateModel(
            name='当前的HA访问量',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('times', models.CharField(max_length=100)),
            ],
        ),
    ]
