# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_告警情况'),
    ]

    operations = [
        migrations.AddField(
            model_name='告警情况',
            name='times',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
