# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_告警情况_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='服务响应时间和当前状态',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('服务名称', models.CharField(max_length=100)),
                ('北京探测点响应时间', models.CharField(max_length=100)),
                ('上海探测点响应时间', models.CharField(max_length=100)),
                ('北京探测点北京探测点', models.CharField(max_length=100)),
                ('上海探测点北京探测点', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=100)),
            ],
        ),
    ]
