# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_服务响应时间和当前状态'),
    ]

    operations = [
        migrations.RenameField(
            model_name='服务响应时间和当前状态',
            old_name='上海探测点北京探测点',
            new_name='上海探测点当前状态',
        ),
        migrations.RenameField(
            model_name='服务响应时间和当前状态',
            old_name='北京探测点北京探测点',
            new_name='北京探测点当前状态',
        ),
    ]
