# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20170713_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='网络情况',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('北京', models.CharField(max_length=100)),
                ('上海', models.CharField(max_length=100)),
                ('广州', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=100)),
            ],
        ),
    ]
