# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_网络情况'),
    ]

    operations = [
        migrations.AddField(
            model_name='网络情况',
            name='上海可用性',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='网络情况',
            name='北京可用性',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='网络情况',
            name='广州可用性',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
