# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20170713_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='网络情况',
            old_name='上海可用性',
            new_name='上海网络可用性',
        ),
        migrations.RenameField(
            model_name='网络情况',
            old_name='北京可用性',
            new_name='北京网络可用性',
        ),
        migrations.RenameField(
            model_name='网络情况',
            old_name='广州可用性',
            new_name='广州网络可用性',
        ),
    ]
