# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20170713_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='网络情况',
            name='上海网络可用性',
        ),
        migrations.RemoveField(
            model_name='网络情况',
            name='广州网络可用性',
        ),
    ]
