# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_网络情况_广州网络可用性'),
    ]

    operations = [
        migrations.RenameField(
            model_name='网络情况',
            old_name='上海',
            new_name='上海网络情况',
        ),
        migrations.RenameField(
            model_name='网络情况',
            old_name='北京',
            new_name='北京网络情况',
        ),
        migrations.RenameField(
            model_name='网络情况',
            old_name='广州',
            new_name='广州网络情况',
        ),
    ]
