# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_redis命中率'),
    ]

    operations = [
        migrations.CreateModel(
            name='七牛用量',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('存储', models.CharField(max_length=100)),
                ('CDN', models.CharField(max_length=100)),
                ('带宽', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='当前数据库QPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostgreSQL', models.CharField(max_length=100)),
                ('MySQL', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='青云用量',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('云服务器', models.IntegerField()),
                ('路由器', models.IntegerField()),
                ('硬盘', models.IntegerField()),
                ('IP地址', models.IntegerField()),
                ('times', models.CharField(max_length=100)),
            ],
        ),
    ]
