# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_七牛用量_当前数据库qps_青云用量'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDN_带宽',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=100)),
            ],
        ),
    ]
