# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_cdn_带宽'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdn_带宽',
            name='value',
            field=models.IntegerField(),
        ),
    ]
