# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20170717_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdn_带宽',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
