# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_cdn_带宽_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDN_回源带宽',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField()),
                ('times', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CDN_总流量',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField()),
                ('times', models.CharField(max_length=100)),
            ],
        ),
    ]
