# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_cdn_回源带宽_cdn_总流量'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CDN_总流量',
            new_name='CDN_流量',
        ),
    ]
