# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_auto_20170718_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='二十四小时服务器可用率',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('times', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
