# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_二十四小时服务器可用率'),
    ]

    operations = [
        migrations.AlterField(
            model_name='二十四小时服务器可用率',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
