# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_auto_20170720_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='当前数据库qps',
            name='SSOMySQL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='当前数据库qps',
            name='SSOPostgreSQL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='当前数据库qps',
            name='电商MySQL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='当前数据库qps',
            name='电商PostgreSQL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
