# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_auto_20170720_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='当前数据库qps',
            name='MySQL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='当前数据库qps',
            name='PostgreSQL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
