# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_auto_20170720_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='当前数据库qps',
            name='MySQL',
        ),
        migrations.RemoveField(
            model_name='当前数据库qps',
            name='PostgreSQL',
        ),
    ]
